language: erlang

sudo: required

before_install:
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo sh -c "echo deb https://apt.dockerproject.org/repo ubuntu-precise main > /etc/apt/sources.list.d/docker.list"
  - sudo apt-get update
  - sudo apt-get install docker-engine
  - sudo docker info
  - curl -L https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin/
  - git clone https://github.com/erlang/rebar3.git; cd rebar3; ./bootstrap; sudo cp rebar3 /usr/bin; cd ..

notifications:
  email: false

otp_release:
  - 18.2.1
  - 17.5

script:
  - set -e
  - make vsn-check
  - scripts/line-width-check.sh

  - echo "verifying rebar compilation"
  - rebar get-deps
  - rebar compile

  - make distclean
  - echo "verifying rebar3 compilation"
  - rebar3 compile

  - export BROD_CLI=true
  - make distclean
  - make rel
  - make edoc
  - make xref
  - make test-env
  - make t

