language: erlang

sudo: required

services:
  - docker

# install latest rebar3 because the one travis provides doesn't support cover_export_name option
before_install:
  - git clone https://github.com/erlang/rebar3.git; cd rebar3; ./bootstrap; sudo mv rebar3 /usr/local/bin/; cd ..
  - git clone https://github.com/inaka/elvis.git; cd elvis; rebar3 escriptize; sudo cp _build/default/bin/elvis /usr/bin; cd ..
  - sudo docker info

notifications:
  email: false

otp_release:
  - 21.0
  - 20.3
  - 19.3

script:
  # check style first
  - elvis rock

  # test compilation with rebar
  - rebar get-deps
  - rebar compile

  # test with rebar3
  - make distclean
  - rebar3 compile

  - make distclean
  - rebar3 edoc
  - rebar3 xref
  - make brod-cli
  - |
    set -e
    OTP_VSN=`erl -noshell -eval 'io:format(erlang:system_info(otp_release)), halt(0)'`
    if [ $OTP_VSN -eq 21 ]; then
      # run dialyzer only in otp 21
      rebar3 dialyzer
      # test against kafka 0.9 in otp 21
      export KAFKA_VERSION="0.9"
    fi
    if [ $OTP_VSN -eq 20 ]; then
      # test against kafka 0.10 in otp 20
      export KAFKA_VERSION="0.10"
    fi
    if [ $OTP_VSN -eq 19 ]; then
      # test against kafka 0.11 in otp 19
      export KAFKA_VERSION="0.11"
    fi
    make test-env
    _build/brod_cli/rel/brod/bin/brod meta -b localhost -L
    make it
    # final full test against kafka 1.1
    export KAFKA_VERSION="1.1"
    make test-env
    make t
    make cover

after_success:
  - |
    OTP_VSN=`erl -noshell -eval 'io:format(erlang:system_info(otp_release)), halt(0)'`
    if [ $OTP_VSN -eq 21 ]; then
      make coveralls
    fi

